#!/bin/sh
#
# Hook for TPM-LUKS decryption
#

PREREQ=""

prereqs()

 {

   echo "$PREREQ"

 }

case $1 in

 prereqs)

   prereqs

   exit 0

   ;;

esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/sbin/tpm2_nvread

copy_exec /usr/bin/perl

exit 0
